frr version 8.4_git
frr defaults traditional
hostname r4
log stdout
no ipv6 forwarding
!
interface eth1
 ip address 10.0.45.0/31
 ip router isis 0
 isis network point-to-point
exit
!
interface eth2
 ip address 10.0.46.0/31
 ip router isis 0
 isis network point-to-point
exit
!
interface eth3
 ip address 10.0.34.1/31
 ip router isis 0
 isis network point-to-point
exit
!
interface lo
 ip address 4.4.4.4/32
 ip router isis 0
 isis passive
exit
!
router ospf
 network 4.4.4.4/32 area 0
exit
!
router isis 0
 net 49.0001.0000.0000.0004.00
exit
!
