frr version 8.4_git
frr defaults traditional
hostname r6
log stdout
no ipv6 forwarding
!
interface eth1
 ip address 10.0.46.1/31
 ip router isis 0
 isis network point-to-point
exit
!
interface eth2
 ip address 10.0.56.1/31
 ip router isis 0
 isis network point-to-point
exit
!
interface eth3
 ip address 10.255.2.1/30
 ip router isis 0
 isis passive
exit
!
interface lo
 ip address 6.6.6.6/32
 ip router isis 0
 isis passive
exit
!
router bgp 66006
 bgp router-id 6.6.6.6
 no bgp ebgp-requires-policy
 no bgp network import-check
 timers bgp 10 30
 neighbor 1.1.1.1 remote-as 66001
 neighbor 1.1.1.1 ebgp-multihop 255
 neighbor 1.1.1.1 update-source lo
 !
 address-family ipv4 unicast
  network 10.255.2.0/30
 exit-address-family
exit
!
router ospf
 network 6.6.6.6/32 area 0
exit
!
router isis 0
 net 49.0001.0000.0000.0006.00
exit
!
