hostname frr1
service integrated-vtysh-config
log stdout

interface eth0
 ip address 192.168.100.101/24

interface lo
 ip address 1.1.1.1/32

router ospf
 network 192.168.100.0/24 area 0
 network 1.1.1.1/32 area 0
