conf t
    router isis 0

int lo
 ip router isis 0
 isis passive

interface eth1
 ip router isis 0
 isis network point-to-point
interface eth2
 ip router isis 0
 isis network point-to-point
interface eth3
 ip router isis 0
 isis network point-to-point